version: '2'
services:
  mysql:
    image: mysql:5.7.31
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret

  bookstack-cms:
    image: bookstack-cms
    build: .
    ports: 
      - 8080:8080
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret

